# Generated by Django 3.1.6 on 2021-02-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='component',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
