# Generated by Django 3.1.4 on 2021-02-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_permission_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='model',
        ),
    ]
