# Generated by Django 3.1.6 on 2021-02-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20210220_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='path',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
