# Generated by Django 3.1.6 on 2021-02-19 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20210219_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=20)),
                ('is_active', models.IntegerField(default=1)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.menu')),
            ],
            options={
                'verbose_name_plural': '权限',
                'db_table': 'tb_permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('menus', models.ManyToManyField(related_name='roles', to='rbac.Menu')),
                ('permissions', models.ManyToManyField(related_name='roles', to='rbac.Permission')),
                ('users', models.ManyToManyField(related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '角色',
                'db_table': 'tb_role',
            },
        ),
    ]
