# Generated by Django 3.1.6 on 2021-02-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20210220_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
