# Generated by Django 3.1.6 on 2021-02-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20210220_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='url',
            new_name='method',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='is_active',
        ),
        migrations.AddField(
            model_name='permission',
            name='model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
